services:
  - name: frontend
    type: web
    buildCommand: |
      cd client
      npm install --f
      npm run build
    startCommand: npm start
    env: 
      - name: NODE_ENV
        value: production

  - name: backend
    type: web
    buildCommand: npm install
    startCommand: npm start
    env:
      - name: NODE_ENV
        value: production
